### Question on Classification

#### Problem Statement

You are asked to predict the likelihood of the person having a bank account or not (Yes = 1, No = 0), for each unique id in the test dataset . You will train your model on 70% of the data and test your model on the final 30% of the data, across four East African countries - Kenya, Rwanda, Tanzania, and Uganda.

In [1]:
### CRISP-DM framework

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

### Data Dictionary

In [18]:
df = pd.read_csv('Data_sets/VariableDefinitions.csv', sep=',')

In [19]:
df

      Variable Definitions                                         Unnamed: 1
0                  country                         Country interviewee is in.
1                     year                           Year survey was done in.
2                 uniqueid             Unique identifier for each interviewee
3            location_type                     Type of location: Rural, Urban
4         cellphone_access  If interviewee has access to a cellphone: Yes, No
5           household_size               Number of people living in one house
6        age_of_respondent                         The age of the interviewee
7     gender_of_respondent                Gender of interviewee: Male, Female
8   relationship_with_head  The interviewee’s relationship with the head o...
9           marital_status  The martial status of the interviewee: Married...
10         education_level  Highest level of education: No formal educatio...
11                job_type  Type of job interviewee has: Farming and Fishi...

In [21]:
df = pd.read_csv('Data_sets/Train.csv', sep=',')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   bank_account            23524 non-null  object
 4   location_type           23524 non-null  object
 5   cellphone_access        23524 non-null  object
 6   household_size          23524 non-null  int64
 7   age_of_respondent       23524 non-null  int64
 8   gender_of_respondent    23524 non-null  object
 9   relationship_with_head  23524 non-null  object
 10  marital_status          23524 non-null  object
 11  education_level         23524 non-null  object
 12  job_type                23524 non-null  object
dtypes: int64(3), object(10)
memory usage: 2.3+ MB

columns can be grouped into features (inputs) and labels (output).

There is usually 1 output -bank_account. the rest of the columns are features/inputs

In [23]:
df.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

In [24]:
# clas imbalance

df['bank_account'].value_counts()

bank_account
No     20212
Yes     3312
Name: count, dtype: int64

In [28]:
df['bank_account'] = df['bank_account'].replace({
    'Yes': 1,
    'No' : 0
})

In [29]:
df

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,1,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,0,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,1,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,0,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,0,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23519,Uganda,2018,uniqueid_2113,0,Rural,Yes,4,48,Female,Head of Household,Divorced/Seperated,No formal education,Other Income
23520,Uganda,2018,uniqueid_2114,0,Rural,Yes,2,27,Female,Head of Household,Single/Never Married,Secondary education,Other Income
23521,Uganda,2018,uniqueid_2115,0,Rural,Yes,5,27,Female,Parent,Widowed,Primary education,Other Income
23522,Uganda,2018,uniqueid_2116,0,Urban,Yes,7,30,Female,Parent,Divorced/Seperated,Secondary education,Self employed
23523,Uganda,2018,uniqueid_2117,0,Rural,Yes,10,20,Male,Child,Single/Never Married,Secondary education,No Income

In [30]:
df.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,1,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,0,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,1,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,0,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,0,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

Data Understanding.

The data provided presents the countries , the year, each country unique id , their locations and corresponding bank account.

In [31]:
x = df.drop('bank_account', axis=1)
y = df.bank_account

In [32]:
x

,country,year,uniqueid,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed
...,...,...,...,...,...,...,...,...,...,...,...,...
23519,Uganda,2018,uniqueid_2113,Rural,Yes,4,48,Female,Head of Household,Divorced/Seperated,No formal education,Other Income
23520,Uganda,2018,uniqueid_2114,Rural,Yes,2,27,Female,Head of Household,Single/Never Married,Secondary education,Other Income
23521,Uganda,2018,uniqueid_2115,Rural,Yes,5,27,Female,Parent,Widowed,Primary education,Other Income
23522,Uganda,2018,uniqueid_2116,Urban,Yes,7,30,Female,Parent,Divorced/Seperated,Secondary education,Self employed
23523,Uganda,2018,uniqueid_2117,Rural,Yes,10,20,Male,Child,Single/Never Married,Secondary education,No Income

In [33]:
y

0        1
1        0
2        1
3        0
4        0
        ..
23519    0
23520    0
23521    0
23522    0
23523    0
Name: bank_account, Length: 23524, dtype: int64

In [34]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   location_type           23524 non-null  object
 4   cellphone_access        23524 non-null  object
 5   household_size          23524 non-null  int64
 6   age_of_respondent       23524 non-null  int64
 7   gender_of_respondent    23524 non-null  object
 8   relationship_with_head  23524 non-null  object
 9   marital_status          23524 non-null  object
 10  education_level         23524 non-null  object
 11  job_type                23524 non-null  object
dtypes: int64(3), object(9)
memory usage: 2.2+ MB

### Encoding
- Label Encoding
- One hot Encoding

replace does something similar to label encoding

In [36]:
#### Feature Selection

X_selected = x.drop(['country', 'year', 'uniqueid', 'gender_of_respondent'], axis=1)

In [37]:
X_selected

,location_type,cellphone_access,household_size,age_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Rural,Yes,3,24,Spouse,Married/Living together,Secondary education,Self employed
1,Rural,No,5,70,Head of Household,Widowed,No formal education,Government Dependent
2,Urban,Yes,5,26,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Rural,Yes,5,34,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Urban,No,8,26,Child,Single/Never Married,Primary education,Informally employed
...,...,...,...,...,...,...,...,...
23519,Rural,Yes,4,48,Head of Household,Divorced/Seperated,No formal education,Other Income
23520,Rural,Yes,2,27,Head of Household,Single/Never Married,Secondary education,Other Income
23521,Rural,Yes,5,27,Parent,Widowed,Primary education,Other Income
23522,Urban,Yes,7,30,Parent,Divorced/Seperated,Secondary education,Self employed
23523,Rural,Yes,10,20,Child,Single/Never Married,Secondary education,No Income

In [38]:
from sklearn.preprocessing import LabelEncoder

labelEncoder = LabelEncoder()

In [39]:
X_selected['location_type'] = labelEncoder.fit_transform(X_selected['location_type'])
X_selected['cellphone_access'] = labelEncoder.fit_transform(X_selected['cellphone_access'])
X_selected['relationship_with_head'] = labelEncoder.fit_transform(X_selected['relationship_with_head'])
X_selected['marital_status'] = labelEncoder.fit_transform(X_selected['marital_status'])
X_selected['education_level'] = labelEncoder.fit_transform(X_selected['education_level'])
X_selected['job_type'] = labelEncoder.fit_transform(X_selected['job_type'])

In [40]:
X_selected

,location_type,cellphone_access,household_size,age_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,0,1,3,24,5,2,3,9
1,0,0,5,70,1,4,0,4
2,1,1,5,26,3,3,5,9
3,0,1,5,34,1,2,2,3
4,1,0,8,26,0,3,2,5
...,...,...,...,...,...,...,...,...
23519,0,1,4,48,1,0,0,7
23520,0,1,2,27,1,3,3,7
23521,0,1,5,27,4,4,2,7
23522,1,1,7,30,4,0,3,9
23523,0,1,10,20,0,3,3,6

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.3, random_state=0, stratify=y)

In [42]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [43]:
model.fit(X_train, y_train)

LogisticRegression()

In [44]:
from sklearn.metrics import accuracy_score, classification_report

predictions = model.predict(X_test)

In [45]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.88      0.98      0.93      6064
           1       0.67      0.21      0.32       994

    accuracy                           0.87      7058
   macro avg       0.77      0.60      0.63      7058
weighted avg       0.85      0.87      0.84      7058

In [46]:
print(f'Accuracy score : {accuracy_score(y_test,predictions)}')

Accuracy score : 0.8740436384244828